### ISSUE TITLE
Thanks for resurrecting the project!

### ISSUE THREAD

**Issue by DarthGandalf** [janikrabe/oidentd#14]

**Comment by janikrabe** [comment]
I'm glad you like it. If you have any feedback or suggestions for the project, please let me know!

**Comment by DarthGandalf** [comment]
Well, you fixed some issues which I had with 2.0.8.
Please add Alpine to https://github.com/janikrabe/oidentd/projects/3 (https://bugs.alpinelinux.org/issues/8882), otherwise no immediate suggestions :)

**Comment by janikrabe** [comment]
Done. Thanks! :+1:
