### ISSUE TITLE
Build error: error: parameter name omitted

### ISSUE THREAD

**Issue by solbu** [janikrabe/oidentd#16]
When building on Mageia, I get this error:

> gcc -DHAVE_CONFIG_H -I. -I..  -I "./missing" -D "SYSCONFDIR=\"/etc\""    -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC -std=gnu89 -MT os.o -MD -MP -MF .deps/os.Tpo -c -o os.o os.c
os.c: In function 'callback_nfct':
os.c:181:31: error: parameter name omitted
 static int callback_nfct(enum nf_conntrack_msg_type,
                               ^
os.c: In function 'masq':
os.c:469:19: error: 'CT_LIBNFCT' undeclared (first use in this function)
  if (conntrack == CT_LIBNFCT) {
                   ^
os.c:469:19: note: each undeclared identifier is reported only once for each function it appears in
os.c:470:11: error: expected expression before '{' token
   query = { sock, lport, fport, laddr, faddr, 1 };
           ^
Makefile:477: recipe for target 'os.o' failed
make[3]: *** [os.o] Error 1
make[3]: Leaving directory '/home/solbu/mageia-rpm/oidentd/BUILD/oidentd-2.3.0/src'
Makefile:503: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/solbu/mageia-rpm/oidentd/BUILD/oidentd-2.3.0/src'
Makefile:660: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/solbu/mageia-rpm/oidentd/BUILD/oidentd-2.3.0/src'
Makefile:430: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
error: Bad exit status from /home/solbu/mageia-rpm/oidentd/BUILDROOT/rpm-tmp.OPcOzB (%install)

**Comment by solbu** [comment]
Forgot to mention it is version 2.3.0.

**Comment by janikrabe** [comment]
Sorry about that. That's been fixed in bae6665063eef92ddcb9d7c53fcbf37165e9605d, thanks for letting me know!
