### ISSUE TITLE
Intent to deprecate: libudb support

### ISSUE THREAD

**Issue by janikrabe** [janikrabe/oidentd#18]
libudb (user database library) is a library that intends to provide an abstraction layer for looking up user information. It serves as an alternative to oidentd's built-in kernel interface, and can also integrate with other programs such as RADIUS servers.

However, libudb has been unmaintained for more than ten years, and it is doubtful whether it compiles with any recent kernels. I'm also unable to find a download link for the library, although I did find the project webpage earlier this year.

I'm planning to **deprecate** libudb support in the next release, and **remove** it entirely from the following major release. If anyone still uses oidentd with libudb, please let me know.

Currently, libudb is used if oidentd is run with the `--udb` (`-U`) flag. The command `oidentd --version` shows whether oidentd was compiled with support for libudb.

**Comment by janikrabe** [comment]
Deprecated in 62c4c9fdc421eff524b2195996b30eca3b817664.

**Comment by gumbie02151** [comment]
Well that isn't cool!  I use udb, infact I was hoping to expand on the concept.. As my NAT router is an ASA 5520, that forwards 113 incoming to the machine I IRC from. I was hoping to make a IRC client script to maintain IDENT entries in a db, that oidentd looks at, as it has no access to the routers NAT tables.. This would make it also possible to use other clients on the lan having that oidentd process act as a master working from a DB as opposed from NAT / Masq tables...

**Comment by janikrabe** [comment]
Hi @gumbie02151, thanks for letting me know! I'm happy to revert these changes if libudb is still used.

Could you let me know where you downloaded libudb from? Or did you build your own library that links against oidentd's libudb interface?

**Comment by janikrabe** [comment]
@gumbie02151, would you still like to get this change reverted?

**Comment by janikrabe** [comment]
For future reference, the libudb website is still available at <http://bre.klaki.net/programs/udb/>. However, the last update was in May 2000 and, according to the README, it has only been verified to work on HP-UX 10.20, which is unsupported by oidentd, and Linux 2.2.13, which is EOL.
