### ISSUE TITLE
ERROR:NO-USER in alpine docker

### ISSUE THREAD

**Issue by hgl** [janikrabe/oidentd#35]
I'm using 2.4.0 in alpine 10.3 within docker. With the following configs, oidentd always returns `ERROR:NO-USER` for my nc test:

```
$ cat /etc/oidentd.conf
user znc {
    default {
        allow spoof
        allow spoof_all
    }
}
```
```
$ cat /home/znc/.oidentd.conf
global { reply "abc" }
```
```
$ stat -c '%a' /home/znc
711
```
```
$ stat -c '%U %G %a' /home/znc/.oidentd.conf
znc nogroup 644
```
```
$ cat /etc/passwd | grep znc
znc:x:100:65533:Linux User,,,:/home/znc:/sbin/nologin
```

oidentd is run with

```
oidentd --foreground --nosyslog
```
configure options

```
./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --disable-nat \
        --disable-libnfct \
        --disable-xdgbdir
```
and the nc command

```
$ nc 1.1.1.1 113 
1,1
1,1:ERROR:NO-USER
```
where 1.1.1.1 is the server's public ip.

From the doc, I expect no matter what ports are given, it should return user id abc.

What did I miss?

**Comment by janikrabe** [comment]
Hi,

This is the intended behavior. If the documentation is unclear or confusing I'd like to change that; could you let me know which part of the documentation you're referring to?

User configuration files like `~znc/.oidentd.conf` are read only after a connection is determined to belong to the user in question.

If you always want to send the same reply, even if a connection doesn't exist, you can run oidentd with the `-R` (`--reply-all`) option. However, this feature isn't available in version 2.4.0 yet, so you would have to build oidentd from git.

Alternatively, if you'd rather use 2.4.0, you can use the `-r` (`--reply`) option in combination with this `/etc/oidentd.conf` file:

```
default {
    default {
        force reply "abc"
    }
}
```

The `--reply` option handles failed lookups, while the configuration file handles successful ones.
However, this isn't ideal, as unnecessary connection lookups will still be performed (unlike with `--reply-all`).

**Comment by hgl** [comment]
Thanks for the quick reply Janik.

> User configuration files like ~znc/.oidentd.conf are read only after a connection is determined to belong to the user in question.

This enlightens me. I was trying to make oidentd work with znc. I initially thought it worked by having znc made changes to `~znc/.oidentd.conf`, and oidentd would automatically pick up and return that ident for any ports during the change.

I put oident and znc in separate docker containers, was pulling my hair off wondering why it couldn't work.

But that comment made it all clear. Thanks. I think if the doc could mention that, it would be of great help.

Now the next question is: is it possible to make the separate docker containers scenario work?

**Comment by janikrabe** [comment]
> I think if the doc mentioned that, it would be of great help.

That should be doable!

> Now the next question is: is it possible to make the separate docker containers scenario work?

That's tricky. It's possible if you don't mind running another oidentd instance in the ZNC container, but I'm guessing that would defeat the purpose of having two different containers.

Because Docker containers are isolated from each other, you would need some mechanism oidentd could use to communicate with ZNC. This could an additional server that returns the contents of a file written by ZNC's `*identfile` module, or some way of synchronizing ZNC's configuration file between both containers (as long as the synchronization happens before ZNC connects to the server).
Unfortunately, I can't think of an easy and reliable way to do this.

**Comment by hgl** [comment]
I'll try the multi-process approach, thanks for the help.

**Comment by hgl** [comment]
Aftering experimenting more, it seems multi-container couldn't seem to work either, because by using docker, I basically put oidentd and znc behind a NAT, and there is no guarantee the port opened by znc is the one used to connect to IRC server, so oidentd could still fail?

Does that mean oidentd should be run on host network?

**Comment by janikrabe** [comment]
I'm not too familiar with Docker, but you're correct, ident doesn't work reliably through NAPT.
Running oidentd on the host as you suggested is probably the easiest option (aside from disabling port translation, if that's possible.)

oidentd does have the ability to forward queries to another ident server (`--forward`, `--proxy`) but that would mean you'd have to run two instances, one of them on the host machine, and you'd still have to allow the oidentd container to read `~znc/.oidentd.conf` in the other container.

Another option would be to use the [`*identserver` ZNC module](https://wiki.znc.in/Using_ident_spoofs_with_identserver_and_iptables) with oidentd on the host to take care of the NAPT issue. Of course that would mean having to run an ident server in the ZNC container, and you'd need an oidentd instance running on the host anyway.
