### ISSUE TITLE
use oidentd on macos

### ISSUE THREAD

**Issue by dfuriet** [janikrabe/oidentd#39]
Hi, 

It's possible to adapt oidentd to macos ?

When I trying to run  ./configure :
(...)
checking for getopt_long... yes
checking for setgroups... yes
checking for unveil... no
checking for library containing socket... none required
checking for getaddrinfo... yes
checking for freeaddrinfo... yes
checking for gai_strerror... yes
checking for getnameinfo... yes
checking for inet_ntop... yes
checking for struct sockaddr_storage... yes
checking for ss_family member in struct sockaddr_storage... yes
checking for struct sockaddr_in6... yes
checking for struct in6_addr... yes
checking for struct addrinfo... yes
checking netinet/ip_compat.h netinet/ip_fil.h netinet/ip_nat.h usability... no
checking netinet/ip_compat.h netinet/ip_fil.h netinet/ip_nat.h presence... no
checking for netinet/ip_compat.h netinet/ip_fil.h netinet/ip_nat.h... no
checking for netinet/ip_nat.h... no
checking for /usr/src/sys/contrib/ipfilter/netinet/ip_nat.h... no
checking if nat_t has nat_p member... no
configure: error: oidentd does not yet support darwin20.5.0

**Comment by janikrabe** [comment]
Hi!

Darwin systems aren't supported at the moment. Someone would have to write a kernel module to add support for it.

We used to support very old versions of Darwin before c025253ba170c83932bf7d025f401543a6981361. This won't compile as-is on recent kernels but could be used as a starting point if anyone is interested in adding support for this.

**Comment by dfuriet** [comment]
Hi. 

With this version, I can configure but I have an error with make: :

(...) 
 -MP -MF .deps/options.Tpo -c -o options.o options.c
mv -f .deps/options.Tpo .deps/options.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I "./missing" -D "SYSCONFDIR=\"/usr/local/etc\""    -g -O2 -MT masq.o -MD -MP -MF .deps/masq.Tpo -c -o masq.o masq.c
mv -f .deps/masq.Tpo .deps/masq.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I "./missing" -D "SYSCONFDIR=\"/usr/local/etc\""    -g -O2 -MT cfg_scan.o -MD -MP -MF .deps/cfg_scan.Tpo -c -o cfg_scan.o cfg_scan.c
mv -f .deps/cfg_scan.Tpo .deps/cfg_scan.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I "./missing" -D "SYSCONFDIR=\"/usr/local/etc\""    -g -O2 -MT cfg_parse.o -MD -MP -MF .deps/cfg_parse.Tpo -c -o cfg_parse.o cfg_parse.c
mv -f .deps/cfg_parse.Tpo .deps/cfg_parse.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I "./missing" -D "SYSCONFDIR=\"/usr/local/etc\""    -g -O2 -MT os.o -MD -MP -MF .deps/os.Tpo -c -o os.o os.c
os.c:26:10: fatal error: 'kvm.h' file not found

**Comment by janikrabe** [comment]
@dfuriet, the module removed in c025253ba170c83932bf7d025f401543a6981361 is only compatible with very old versions of Darwin; it has not been updated since at least the release of Darwin 9. Darwin 20 is not supported (and will not be, unless someone is willing to write a module for it).

**Comment by janikrabe** [comment]
I don't think there's much demand for Darwin support so I'm going to close this. If someone does want to send me a patch that works with recent Darwin kernels I'm happy to review it. The old module I removed in c025253ba170c83932bf7d025f401543a6981361 would probably be a good starting point.
