### ISSUE TITLE
constantly reporting ERROR : NO-USER

### ISSUE THREAD

**Issue by gregbert42** [janikrabe/oidentd#40]
I have compiled version 2.5.0
run with 'sudo ./oidentd -i -d'

'ls -i -P' output includes:
adb      3464845 gregbert    9u  IPv4 124223527      0t0  TCP www:57408->192.168.2.114:5555 (ESTABLISHED)

so i telnet localhost 113 and give:
[me]: 57408,5555
[oidentd response]: 57408,5555:ERROR:NO-USER

I have tried multiple config configurations, including no config so it is using defaults

What did work: 'sudo oidentd -i -u root -g root -r test' - this correctly returns 'test', but still the lookup fails.

```
oidentd 2.5.0 by Janik Rabe <info@janikrabe.com>
Originally written by Ryan McCabe <ryan@numb.org>
https://janikrabe.com/projects/oidentd/

Build information:
        Kernel driver:         linux.c
        Needs kmem access:     No
        Needs root access:     No
        Debug build:           Yes
        Masquerading support:  Yes
        IPv6 support:          Yes
        Linux libnfct support: Yes

Build settings:
        Configuration directory:   /usr/local/etc
        User configuration file:   ~/.config/oidentd.conf
        User configuration file:   ~/.oidentd.conf
```

Linux 5.10.21-1-lts x86_64
Archlinux

Am I doing something wrong?

**Comment by janikrabe** [comment]
Hi @gregbert42, the IP address you use to connect to oidentd needs to match the remote address of the connection you're querying. You won't be able to query oidentd from localhost unless you're asking about a localhost-to-localhost connection.

**Comment by gregbert42** [comment]
I am sure that is it. thank you @janikrabe .
